name: CI
on:
  push
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      - name: Package
        run: zip Coop.zip -r Coop/
      - name: Bump version and push tag
        id: tag
        uses: anothrNick/github-tag-action@4ed44965e0db8dab2b466a16da04aec3cc312fd8 # v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
      - uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd # v1
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          artifacts: "Coop.zip"
          generateReleaseNotes: true
          tag: ${{ steps.tag.outputs.new_tag }}
