name: CI
on: push
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Package
        run: zip Coop.zip -r Coop/
      - name: Bump version and push tag
        id: tag
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
      - uses: ncipollo/release-action@v1
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          artifacts: "Coop.zip"
          generateReleaseNotes: true
          tag: ${{ steps.tag.outputs.new_tag }}
