name: TechDocs
on:
  push: {}
jobs:
  techdocs:
    permissions:
      contents: read
      id-token: write
      packages: read
    name: TechDocs
    uses: coopnorge/github-workflow-techdocs/.github/workflows/techdocs.yaml@v0
